# Generated by Django 5.0.9 on 2025-09-17 20:30

import depot.mixins.timestamp
import depot.models.revisionmixin
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="active",
                        max_length=255,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("clinical", "Clinical"), ("interval", "Interval")],
                        default="clinical",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                models.Model,
                depot.models.revisionmixin.RevisionMixin,
                depot.mixins.timestamp.TimestampMixin,
            ),
        ),
        migrations.CreateModel(
            name="DataFileType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("label", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order for file types"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
            bases=(
                models.Model,
                depot.models.revisionmixin.RevisionMixin,
                depot.mixins.timestamp.TimestampMixin,
            ),
        ),
        migrations.CreateModel(
            name="ProtocolYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-year", "name"],
            },
            bases=(
                models.Model,
                depot.models.revisionmixin.RevisionMixin,
                depot.mixins.timestamp.TimestampMixin,
            ),
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=(
                models.Model,
                depot.models.revisionmixin.RevisionMixin,
                depot.mixins.timestamp.TimestampMixin,
            ),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When the activity occurred",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("login_failed", "Login Failed"),
                            ("session_timeout", "Session Timeout"),
                            ("force_logout", "Force Logout"),
                            ("page_access", "Page Access"),
                            ("api_access", "API Access"),
                            ("file_download", "File Download"),
                            ("report_view", "Report View"),
                            ("export_data", "Data Export"),
                            ("permission_change", "Permission Change"),
                            ("user_create", "User Create"),
                            ("user_modify", "User Modify"),
                            ("admin_access", "Admin Access"),
                            ("data_create", "Data Create"),
                            ("data_update", "Data Update"),
                            ("data_delete", "Data Delete"),
                            ("data_export", "Data Export"),
                        ],
                        db_index=True,
                        help_text="Type of activity performed",
                        max_length=50,
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True, help_text="Whether the activity was successful"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the user", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="User agent string from browser",
                        null=True,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Django session ID",
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "terminal_id",
                    models.CharField(
                        blank=True,
                        help_text="Terminal/workstation identifier for compliance",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        help_text="URL path accessed",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        help_text="HTTP method (GET, POST, etc.)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "status_code",
                    models.IntegerField(
                        blank=True, help_text="HTTP response status code", null=True
                    ),
                ),
                (
                    "duration_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Request duration in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional activity-specific data",
                    ),
                ),
                (
                    "retention_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when record can be deleted (NULL = indefinite retention)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the activity (null for anonymous)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "permissions": [
                    ("export_activities", "Can export activity logs"),
                    ("view_all_activities", "Can view all user activities"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CohortMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="depot.cohort"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                models.Model,
                depot.models.revisionmixin.RevisionMixin,
                depot.mixins.timestamp.TimestampMixin,
            ),
        ),
        migrations.AddField(
            model_name="cohort",
            name="users",
            field=models.ManyToManyField(
                related_name="cohorts",
                through="depot.CohortMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="CohortSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("signed_off", "Signed Off"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("patient_ids", models.JSONField(blank=True, default=list)),
                ("patient_file_processed", models.BooleanField(default=False)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="General notes about this submission"
                    ),
                ),
                ("final_comments", models.TextField(blank=True)),
                ("final_acknowledged", models.BooleanField(default=False)),
                ("final_acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "signed_off",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when user confirmed all data reviewed and errors corrected",
                        null=True,
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when submission was finalized",
                        null=True,
                    ),
                ),
                (
                    "reopened_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason provided by admin for reopening submission",
                    ),
                ),
                ("reopened_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="depot.cohort",
                    ),
                ),
                (
                    "final_acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reopened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reopened_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="started_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "protocol_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohort_submissions",
                        to="depot.protocolyear",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(
                models.Model,
                depot.models.revisionmixin.RevisionMixin,
                depot.mixins.timestamp.TimestampMixin,
            ),
        ),
        migrations.CreateModel(
            name="DataFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("filename", models.CharField(blank=True, max_length=255, null=True)),
                ("storage_path", models.CharField(max_length=1024)),
                ("file_hash", models.CharField(max_length=64)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="depot.datafiletype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                models.Model,
                depot.models.revisionmixin.RevisionMixin,
                depot.mixins.timestamp.TimestampMixin,
            ),
        ),
        migrations.CreateModel(
            name="CohortSubmissionFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.IntegerField(default=1)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("nas_path", models.CharField(blank=True, max_length=500)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("file_hash", models.CharField(blank=True, max_length=64)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("not_available", "Not Available"),
                        ],
                        default="not_started",
                        help_text="Current status of this file in the submission",
                        max_length=20,
                    ),
                ),
                ("is_skipped", models.BooleanField(default=False)),
                ("skip_reason", models.TextField(blank=True)),
                ("skipped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "not_available",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates cohort doesn't have this data",
                    ),
                ),
                (
                    "not_required",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates this file type is not required for this cohort",
                    ),
                ),
                ("signed_off", models.BooleanField(default=False)),
                ("signed_off_at", models.DateTimeField(blank=True, null=True)),
                ("comments", models.TextField(blank=True)),
                (
                    "error_explanation",
                    models.TextField(
                        blank=True,
                        help_text="Explanation of audit errors/warnings that couldn't be fixed",
                    ),
                ),
                ("validation_warnings", models.JSONField(blank=True, default=dict)),
                ("patient_id_mismatches", models.JSONField(blank=True, default=list)),
                ("warning_count", models.IntegerField(default=0)),
                (
                    "signed_off_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signed_off_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skipped_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="skipped_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="depot.cohortsubmission",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_submission_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "data_file_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_files",
                        to="depot.datafiletype",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
            },
            bases=(
                models.Model,
                depot.models.revisionmixin.RevisionMixin,
                depot.mixins.timestamp.TimestampMixin,
            ),
        ),
        migrations.CreateModel(
            name="CohortSubmissionDataTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("not_available", "Not Available"),
                        ],
                        default="not_started",
                        help_text="Current status of this data table in the submission",
                        max_length=20,
                    ),
                ),
                ("is_skipped", models.BooleanField(default=False)),
                ("skip_reason", models.TextField(blank=True)),
                ("skipped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "not_available",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates cohort doesn't have this data",
                    ),
                ),
                (
                    "not_required",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates this data table is not required for this cohort",
                    ),
                ),
                ("signed_off", models.BooleanField(default=False)),
                ("signed_off_at", models.DateTimeField(blank=True, null=True)),
                ("sign_off_comments", models.TextField(blank=True)),
                ("validation_warnings", models.JSONField(blank=True, default=dict)),
                ("patient_id_mismatches", models.JSONField(blank=True, default=list)),
                ("warning_count", models.IntegerField(default=0)),
                (
                    "signed_off_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signed_off_data_tables",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skipped_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="skipped_data_tables",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_tables",
                        to="depot.cohortsubmission",
                    ),
                ),
                (
                    "data_file_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_data_tables",
                        to="depot.datafiletype",
                    ),
                ),
            ],
            options={
                "ordering": ["data_file_type__order"],
            },
            bases=(
                models.Model,
                depot.models.revisionmixin.RevisionMixin,
                depot.mixins.timestamp.TimestampMixin,
            ),
        ),
        migrations.CreateModel(
            name="DataRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "field_name",
                    models.CharField(
                        help_text="Name of the field that changed", max_length=100
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True,
                        help_text="Previous field value (JSON serialized)",
                        null=True,
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        blank=True,
                        help_text="New field value (JSON serialized)",
                        null=True,
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                        ],
                        help_text="Type of change operation",
                        max_length=20,
                    ),
                ),
                (
                    "backup_reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference to backup system for secondary audit trail",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "encrypted_data",
                    models.BooleanField(
                        default=False,
                        help_text="Whether sensitive data in this revision is encrypted",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "activity",
                    models.ForeignKey(
                        help_text="Activity that caused this data change",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_revisions",
                        to="depot.activity",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Revision",
                "verbose_name_plural": "Data Revisions",
            },
        ),
        migrations.CreateModel(
            name="DataTableFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Custom name for this file (shown when multiple files exist)",
                        max_length=255,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("version", models.IntegerField(default=1)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("file_hash", models.CharField(blank=True, max_length=64)),
                (
                    "raw_file_path",
                    models.CharField(
                        blank=True,
                        help_text="NAS path for raw CSV/TSV file",
                        max_length=500,
                    ),
                ),
                (
                    "duckdb_file_path",
                    models.CharField(
                        blank=True, help_text="NAS path for DuckDB file", max_length=500
                    ),
                ),
                (
                    "duckdb_created_at",
                    models.DateTimeField(
                        blank=True, help_text="When DuckDB file was created", null=True
                    ),
                ),
                (
                    "duckdb_conversion_error",
                    models.TextField(
                        blank=True,
                        help_text="Error message if DuckDB conversion failed",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("validation_warnings", models.JSONField(blank=True, default=dict)),
                ("patient_id_mismatches", models.JSONField(blank=True, default=list)),
                ("warning_count", models.IntegerField(default=0)),
                (
                    "error_explanation",
                    models.TextField(
                        blank=True,
                        help_text="Explanation of audit errors/warnings that couldn't be fixed",
                    ),
                ),
                (
                    "data_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="depot.cohortsubmissiondatatable",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_data_table_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
            bases=(
                models.Model,
                depot.models.revisionmixin.RevisionMixin,
                depot.mixins.timestamp.TimestampMixin,
            ),
        ),
        migrations.CreateModel(
            name="DataTableReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_reviewed",
                    models.BooleanField(
                        default=False,
                        help_text="User has acknowledged reviewing this table",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "comments",
                    models.TextField(
                        blank=True,
                        help_text="Notes about validation issues or other concerns",
                    ),
                ),
                ("comments_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "validation_report_viewed",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically set when user views the validation report",
                    ),
                ),
                (
                    "validation_report_first_viewed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "validation_report_last_viewed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "validation_report_view_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times the validation report was viewed",
                    ),
                ),
                (
                    "has_validation_errors",
                    models.BooleanField(
                        default=False,
                        help_text="Set if validation report contains errors",
                    ),
                ),
                (
                    "has_validation_warnings",
                    models.BooleanField(
                        default=False,
                        help_text="Set if validation report contains warnings",
                    ),
                ),
                (
                    "issue_count",
                    models.IntegerField(
                        default=0, help_text="Total number of validation issues"
                    ),
                ),
                (
                    "comments_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="table_comment_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "data_table",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="depot.cohortsubmissiondatatable",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="table_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "depot_datatable_review",
                "ordering": ["data_table__data_file_type__order"],
            },
            bases=(
                models.Model,
                depot.models.revisionmixin.RevisionMixin,
                depot.mixins.timestamp.TimestampMixin,
            ),
        ),
        migrations.CreateModel(
            name="Notebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("template_path", models.CharField(max_length=1024)),
                (
                    "compiled_path",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("compiling", "Compiling"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("compiled_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="depot.cohort"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "data_file_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="depot.datafiletype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotebookAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "access_method",
                    models.CharField(
                        choices=[
                            ("direct_view", "Direct View"),
                            ("download", "Download"),
                            ("api", "API Access"),
                        ],
                        default="direct_view",
                        max_length=50,
                    ),
                ),
                (
                    "view_duration_seconds",
                    models.IntegerField(
                        blank=True,
                        help_text="How long the report was viewed (if tracked)",
                        null=True,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "data_table",
                    models.ForeignKey(
                        blank=True,
                        help_text="The data table this access is associated with",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notebook_accesses",
                        to="depot.cohortsubmissiondatatable",
                    ),
                ),
                (
                    "notebook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="depot.notebook",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notebook_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "depot_notebook_access",
                "ordering": ["-created_at"],
            },
            bases=(
                models.Model,
                depot.models.revisionmixin.RevisionMixin,
                depot.mixins.timestamp.TimestampMixin,
            ),
        ),
        migrations.CreateModel(
            name="PatientIDValidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "patient_ids",
                    models.JSONField(
                        default=list,
                        help_text="List of valid patient IDs extracted from the patient file",
                    ),
                ),
                (
                    "extracted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When patient IDs were extracted",
                    ),
                ),
                (
                    "total_count",
                    models.IntegerField(
                        default=0, help_text="Total number of patient IDs extracted"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is the current active set of patient IDs",
                    ),
                ),
                (
                    "cohort_submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_validation",
                        to="depot.cohortsubmission",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        help_text="The patient file these IDs were extracted from",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_id_extractions",
                        to="depot.cohortsubmissionfile",
                    ),
                ),
            ],
            options={
                "ordering": ["-extracted_at"],
            },
            bases=(
                models.Model,
                depot.models.revisionmixin.RevisionMixin,
                depot.mixins.timestamp.TimestampMixin,
            ),
        ),
        migrations.CreateModel(
            name="PHIFileTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("nas_raw_created", "Raw file created on NAS"),
                            ("nas_raw_deleted", "Raw file deleted from NAS"),
                            ("nas_duckdb_created", "DuckDB file created on NAS"),
                            ("nas_duckdb_deleted", "DuckDB file deleted from NAS"),
                            ("nas_report_created", "Report created on NAS"),
                            ("nas_report_deleted", "Report deleted from NAS"),
                            ("work_copy_created", "File copied to workspace"),
                            ("work_copy_deleted", "File deleted from workspace"),
                            ("conversion_started", "File conversion started"),
                            ("conversion_completed", "File conversion completed"),
                            ("conversion_failed", "File conversion failed"),
                            (
                                "patient_id_extraction_started",
                                "Patient ID extraction started",
                            ),
                            (
                                "patient_id_extraction_completed",
                                "Patient ID extraction completed",
                            ),
                            (
                                "patient_id_extraction_failed",
                                "Patient ID extraction failed",
                            ),
                            ("file_uploaded_via_stream", "File uploaded via streaming"),
                            ("file_uploaded_chunked", "File uploaded in chunks"),
                            (
                                "file_downloaded_via_stream",
                                "File downloaded via streaming",
                            ),
                            ("file_deleted_via_api", "File deleted via internal API"),
                            (
                                "prefix_deleted_via_api",
                                "Prefix deleted via internal API",
                            ),
                            ("scratch_cleanup", "Scratch directory cleanup"),
                            ("stream_started", "Streaming operation started"),
                            ("stream_completed", "Streaming operation completed"),
                            ("stream_failed", "Streaming operation failed"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(help_text="Full path to the file", max_length=500),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("raw_csv", "Raw CSV file"),
                            ("raw_tsv", "Raw TSV file"),
                            ("duckdb", "DuckDB database"),
                            ("report_html", "HTML report"),
                            ("temp_working", "Temporary working file"),
                            ("patient_data", "Patient data file"),
                            ("workspace_directory", "Workspace directory"),
                            ("unknown", "Unknown file type"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA256 hash of file contents",
                        max_length=64,
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if operation failed"
                    ),
                ),
                (
                    "server_hostname",
                    models.CharField(
                        default="",
                        help_text="Hostname of server where operation occurred",
                        max_length=255,
                    ),
                ),
                (
                    "cleaned_up",
                    models.BooleanField(
                        default=False,
                        help_text="Whether temporary file has been cleaned up",
                    ),
                ),
                (
                    "cleanup_verified_at",
                    models.DateTimeField(
                        blank=True, help_text="When cleanup was verified", null=True
                    ),
                ),
                (
                    "cleanup_required",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this file needs to be cleaned up",
                    ),
                ),
                (
                    "cleanup_attempted_count",
                    models.IntegerField(
                        default=0, help_text="Number of cleanup attempts made"
                    ),
                ),
                (
                    "parent_process_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Process ID that created this file (for orphan detection)",
                        null=True,
                    ),
                ),
                (
                    "expected_cleanup_by",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this file should be cleaned up",
                        null=True,
                    ),
                ),
                (
                    "purpose_subdirectory",
                    models.CharField(
                        blank=True,
                        help_text="Subdirectory for organization (e.g., 'audit', 'upload')",
                        max_length=50,
                    ),
                ),
                (
                    "server_role",
                    models.CharField(
                        blank=True,
                        help_text="Role of server (web/services/testing)",
                        max_length=20,
                    ),
                ),
                (
                    "stream_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="When streaming operation started",
                        null=True,
                    ),
                ),
                (
                    "stream_complete",
                    models.DateTimeField(
                        blank=True,
                        help_text="When streaming operation completed",
                        null=True,
                    ),
                ),
                (
                    "bytes_transferred",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Number of bytes transferred in streaming operation",
                        null=True,
                    ),
                ),
                (
                    "cleanup_scheduled_for",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this file is scheduled for cleanup",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Additional metadata for tracking",
                        null=True,
                    ),
                ),
                (
                    "cleanup_verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_cleanups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cohort this file belongs to (null for system operations)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phi_file_operations",
                        to="depot.cohort",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phi_file_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PHI File Tracking",
                "verbose_name_plural": "PHI File Tracking Records",
                "ordering": ["-created_at"],
            },
            bases=(
                models.Model,
                depot.models.revisionmixin.RevisionMixin,
                depot.mixins.timestamp.TimestampMixin,
            ),
        ),
        migrations.CreateModel(
            name="DataFileSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("validation_report", models.JSONField(blank=True, null=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("signed_at", models.DateTimeField()),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="depot.cohort"
                    ),
                ),
                (
                    "data_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="depot.datafile"
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="depot.datafiletype",
                    ),
                ),
                (
                    "protocol_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="depot.protocolyear",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                models.Model,
                depot.models.revisionmixin.RevisionMixin,
                depot.mixins.timestamp.TimestampMixin,
            ),
        ),
        migrations.CreateModel(
            name="Revision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                        ],
                        max_length=10,
                    ),
                ),
                ("changes", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("model_name", models.CharField(max_length=100)),
                ("object_repr", models.CharField(max_length=500)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("created", "Submission Created"),
                            ("status_changed", "Status Changed"),
                            ("file_uploaded", "File Uploaded"),
                            ("file_approved", "File Approved"),
                            ("file_rejected", "File Rejected"),
                            ("file_skipped", "File Skipped"),
                            ("signed_off", "Signed Off"),
                            ("reopened", "Reopened"),
                            ("comment_added", "Comment Added"),
                            ("patient_ids_extracted", "Patient IDs Extracted"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable description of the activity"
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data related to the activity",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related file if activity is file-specific",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="depot.cohortsubmissionfile",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="depot.cohortsubmission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submission_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission Activity",
                "verbose_name_plural": "Submission Activities",
                "ordering": ["-created_at"],
            },
            bases=(
                models.Model,
                depot.models.revisionmixin.RevisionMixin,
                depot.mixins.timestamp.TimestampMixin,
            ),
        ),
        migrations.CreateModel(
            name="SubmissionPatientIDs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "patient_ids",
                    models.JSONField(
                        default=list,
                        help_text="List of unique patient IDs from the patient file",
                    ),
                ),
                (
                    "patient_count",
                    models.IntegerField(
                        help_text="Total number of unique patient IDs",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "extracted_at",
                    models.DateTimeField(
                        help_text="When the patient IDs were extracted"
                    ),
                ),
                (
                    "extraction_error",
                    models.TextField(
                        blank=True, help_text="Any errors encountered during extraction"
                    ),
                ),
                (
                    "has_duplicates",
                    models.BooleanField(
                        default=False,
                        help_text="Whether duplicate IDs were found and removed",
                    ),
                ),
                (
                    "duplicate_count",
                    models.IntegerField(
                        default=0, help_text="Number of duplicate IDs that were removed"
                    ),
                ),
                (
                    "extracted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_id_extractions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_file",
                    models.ForeignKey(
                        blank=True,
                        help_text="The patient file these IDs were extracted from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_id_extraction",
                        to="depot.datatablefile",
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_ids_record",
                        to="depot.cohortsubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission Patient IDs",
                "verbose_name_plural": "Submission Patient IDs",
                "ordering": ["-extracted_at"],
            },
            bases=(
                models.Model,
                depot.models.revisionmixin.RevisionMixin,
                depot.mixins.timestamp.TimestampMixin,
            ),
        ),
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("storage_path", models.CharField(max_length=1024)),
                ("filename", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("raw", "Raw file"),
                            ("validation_input", "Validation input"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("file_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("keep_until", models.DateTimeField(blank=True, null=True)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
            bases=(
                models.Model,
                depot.models.revisionmixin.RevisionMixin,
                depot.mixins.timestamp.TimestampMixin,
            ),
        ),
        migrations.CreateModel(
            name="FileAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        help_text="ID of the entity this attachment belongs to"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this attachment", max_length=255
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, help_text="Optional comments about this attachment"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                (
                    "file_type",
                    models.CharField(
                        blank=True, help_text="MIME type of the file", max_length=100
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Type of entity this attachment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_file",
                    models.ForeignKey(
                        help_text="Reference to the uploaded file in storage",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="depot.uploadedfile",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
            bases=(
                models.Model,
                depot.models.revisionmixin.RevisionMixin,
                depot.mixins.timestamp.TimestampMixin,
            ),
        ),
        migrations.AddField(
            model_name="datatablefile",
            name="uploaded_file",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to the latest uploaded file version",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="data_table_files",
                to="depot.uploadedfile",
            ),
        ),
        migrations.AddField(
            model_name="cohortsubmissionfile",
            name="uploaded_file",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to the uploaded file in storage",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submission_files",
                to="depot.uploadedfile",
            ),
        ),
        migrations.CreateModel(
            name="UploadPrecheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing_duckdb", "Processing DuckDB"),
                            ("processing_notebook", "Processing Notebook"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                (
                    "file_path",
                    models.CharField(
                        blank=True, help_text="NAS storage path", max_length=500
                    ),
                ),
                ("result", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                (
                    "celery_task_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="depot.cohort",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Deprecated - use uploaded_by instead",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "data_file_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="depot.datafiletype",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_file",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to the uploaded file in storage",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="depot.uploadedfile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(
                models.Model,
                depot.models.revisionmixin.RevisionMixin,
                depot.mixins.timestamp.TimestampMixin,
            ),
        ),
        migrations.AddField(
            model_name="datatablefile",
            name="upload_precheck",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="data_table_files",
                to="depot.uploadprecheck",
            ),
        ),
        migrations.AddField(
            model_name="cohortsubmissionfile",
            name="upload_precheck",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submission_files",
                to="depot.uploadprecheck",
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["user", "timestamp"], name="depot_activ_user_id_4093ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["activity_type", "timestamp"],
                name="depot_activ_activit_1509e1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["session_id", "timestamp"],
                name="depot_activ_session_0739fa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["success", "activity_type"],
                name="depot_activ_success_17bdff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cohortsubmissiondatatable",
            index=models.Index(
                fields=["submission", "data_file_type"],
                name="depot_cohor_submiss_f0cbe0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cohortsubmissiondatatable",
            index=models.Index(
                fields=["submission", "status"], name="depot_cohor_submiss_caf2d5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cohortsubmissiondatatable",
            unique_together={("submission", "data_file_type")},
        ),
        migrations.AddIndex(
            model_name="datarevision",
            index=models.Index(
                fields=["content_type", "object_id", "timestamp"],
                name="depot_datar_content_f9821c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="datarevision",
            index=models.Index(
                fields=["activity", "timestamp"], name="depot_datar_activit_180fec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datarevision",
            index=models.Index(
                fields=["field_name", "change_type"],
                name="depot_datar_field_n_aff78b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notebookaccess",
            index=models.Index(
                fields=["user", "notebook"], name="depot_noteb_user_id_73421b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notebookaccess",
            index=models.Index(
                fields=["data_table", "created_at"],
                name="depot_noteb_data_ta_28ebff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patientidvalidation",
            index=models.Index(
                fields=["cohort_submission", "is_active"],
                name="depot_patie_cohort__d07e2d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="phifiletracking",
            index=models.Index(
                fields=["cohort", "action"], name="depot_phifi_cohort__318306_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phifiletracking",
            index=models.Index(
                fields=["file_path"], name="depot_phifi_file_pa_e2d8b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phifiletracking",
            index=models.Index(
                fields=["cleaned_up", "action"], name="depot_phifi_cleaned_a7beff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phifiletracking",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="depot_phifi_content_678652_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="phifiletracking",
            index=models.Index(
                fields=["cleanup_required", "created_at"], name="idx_cleanup_pending"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cohortsubmission",
            unique_together={("protocol_year", "cohort")},
        ),
        migrations.AddIndex(
            model_name="revision",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="depot_revis_content_e356ef_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="revision",
            index=models.Index(
                fields=["model_name"], name="depot_revis_model_n_2e6dbf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="revision",
            index=models.Index(
                fields=["user", "created_at"], name="depot_revis_user_id_4c26a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submissionactivity",
            index=models.Index(
                fields=["submission", "-created_at"],
                name="depot_submi_submiss_ea3ff8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="submissionactivity",
            index=models.Index(
                fields=["activity_type"], name="depot_submi_activit_be50bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submissionpatientids",
            index=models.Index(
                fields=["submission"], name="depot_submi_submiss_26a097_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submissionpatientids",
            index=models.Index(
                fields=["extracted_at"], name="depot_submi_extract_bcccee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileattachment",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="depot_filea_content_eb7b6b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fileattachment",
            index=models.Index(
                fields=["uploaded_at"], name="depot_filea_uploade_69ccc0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datatablefile",
            index=models.Index(
                fields=["data_table", "is_current"],
                name="depot_datat_data_ta_3a376e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="datatablefile",
            index=models.Index(
                fields=["data_table", "version"], name="depot_datat_data_ta_003d75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cohortsubmissionfile",
            index=models.Index(
                fields=["submission", "data_file_type", "is_current"],
                name="depot_cohor_submiss_f3cc54_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cohortsubmissionfile",
            index=models.Index(
                fields=["submission", "is_current"],
                name="depot_cohor_submiss_3b48f9_idx",
            ),
        ),
    ]
