# Generated by Django 5.0.9 on 2025-09-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissionactivity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("created", "Submission Created"),
                    ("status_changed", "Status Changed"),
                    ("file_uploaded", "File Uploaded"),
                    ("file_approved", "File Approved"),
                    ("file_rejected", "File Rejected"),
                    ("file_skipped", "File Skipped"),
                    ("file_removed", "File Removed"),
                    ("signed_off", "Signed Off"),
                    ("reopened", "Reopened"),
                    ("comment_added", "Comment Added"),
                    ("patient_ids_extracted", "Patient IDs Extracted"),
                ],
                max_length=50,
            ),
        ),
    ]
