# Generated by Django 5.0.9 on 2025-09-22 12:53

import depot.mixins.timestamp
import depot.models.revisionmixin
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depot", "0002_add_file_removed_activity_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataTableFilePatientIDs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "patient_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of patient IDs found in this file",
                    ),
                ),
                (
                    "patient_count",
                    models.IntegerField(
                        default=0, help_text="Total number of unique patient IDs"
                    ),
                ),
                (
                    "valid_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Patient IDs that match the main patient file",
                    ),
                ),
                (
                    "invalid_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Patient IDs not found in the main patient file",
                    ),
                ),
                (
                    "extraction_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the patient IDs were extracted",
                    ),
                ),
                (
                    "extraction_error",
                    models.TextField(
                        blank=True, help_text="Error message if extraction failed"
                    ),
                ),
                (
                    "validated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this file has been validated against main patient file",
                    ),
                ),
                (
                    "validation_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the validation was performed",
                        null=True,
                    ),
                ),
                (
                    "validation_error",
                    models.TextField(
                        blank=True, help_text="Error message if validation failed"
                    ),
                ),
                (
                    "data_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_ids_records",
                        to="depot.datatablefile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Table File Patient IDs",
                "verbose_name_plural": "Data Table File Patient IDs",
                "indexes": [
                    models.Index(
                        fields=["data_file", "validated"],
                        name="depot_datat_data_fi_fc6f78_idx",
                    )
                ],
            },
            bases=(
                models.Model,
                depot.models.revisionmixin.RevisionMixin,
                depot.mixins.timestamp.TimestampMixin,
            ),
        ),
    ]
