# Generated by Django 5.0.9 on 2025-09-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depot", "0003_add_datatablefilepatientids"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohortsubmission",
            name="validation_mode",
            field=models.CharField(
                choices=[
                    ("permissive", "Allow with warnings"),
                    ("strict", "Block if invalid IDs found"),
                ],
                default="permissive",
                help_text="How to handle invalid patient IDs",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cohortsubmission",
            name="validation_threshold",
            field=models.IntegerField(
                default=0,
                help_text="Max invalid IDs allowed before blocking (0 = no tolerance in strict mode)",
            ),
        ),
        migrations.AddField(
            model_name="datatablefilepatientids",
            name="invalid_count",
            field=models.IntegerField(
                default=0, help_text="Number of invalid patient IDs found"
            ),
        ),
        migrations.AddField(
            model_name="datatablefilepatientids",
            name="progress",
            field=models.IntegerField(
                default=0, help_text="Validation progress percentage (0-100)"
            ),
        ),
        migrations.AddField(
            model_name="datatablefilepatientids",
            name="validation_report_url",
            field=models.CharField(
                blank=True,
                help_text="S3 URL for detailed validation report",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="datatablefilepatientids",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("extracting", "Extracting IDs"),
                    ("validating", "Validating"),
                    ("valid", "Valid"),
                    ("invalid", "Invalid IDs Found"),
                    ("error", "Error"),
                ],
                default="pending",
                help_text="Current validation status",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="datatablefilepatientids",
            index=models.Index(
                fields=["data_file", "validation_status"],
                name="depot_datat_data_fi_82ab3e_idx",
            ),
        ),
    ]
