# Generated by Django 5.0.9 on 2025-09-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depot", "0004_add_patient_validation_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileattachment",
            name="file_type",
            field=models.CharField(
                blank=True, help_text="MIME type of the file", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="content_type",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
