# Generated by Django 5.0.9 on 2025-09-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depot", "0005_increase_file_type_field_lengths"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phifiletracking",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("raw_csv", "Raw CSV file"),
                    ("raw_tsv", "Raw TSV file"),
                    ("duckdb", "DuckDB database"),
                    ("report_html", "HTML report"),
                    ("temp_working", "Temporary working file"),
                    ("patient_data", "Patient data file"),
                    ("workspace_directory", "Workspace directory"),
                    ("attachment", "File attachment"),
                    ("submission_attachment", "Submission attachment"),
                    ("unknown", "Unknown file type"),
                ],
                max_length=30,
            ),
        ),
    ]
