# Generated by Django 5.0.9 on 2025-10-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depot", "0006_increase_phifiletracking_file_type_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="storage_disk",
            field=models.CharField(
                default="uploads",
                help_text="Which storage disk this file is stored on (uploads, data, attachments, etc.)",
                max_length=50,
            ),
        ),
    ]
