# Generated by Django 5.0.9 on 2025-10-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depot", "0008_uploadedfile_storage_disk"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sso_email",
            field=models.EmailField(
                blank=True,
                help_text="Email address returned by SAML provider during authentication",
                max_length=254,
                null=True,
                unique=True,
            ),
        ),
    ]
