# Generated by Django 5.0.9 on 2025-10-22 15:50

import depot.mixins.timestamp
import depot.models.revisionmixin
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("depot", "0009_add_sso_email_to_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        help_text="ID of the object being validated"
                    ),
                ),
                (
                    "duckdb_path",
                    models.CharField(
                        help_text="Path to DuckDB file for validation queries",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partially Completed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "total_jobs",
                    models.IntegerField(
                        default=0,
                        help_text="Total number of validation jobs in this run",
                    ),
                ),
                (
                    "completed_jobs",
                    models.IntegerField(
                        default=0,
                        help_text="Number of jobs that have completed (passed or failed)",
                    ),
                ),
                (
                    "failed_jobs",
                    models.IntegerField(
                        default=0, help_text="Number of jobs that failed with errors"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When validation processing started",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When all validation jobs completed",
                        null=True,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Type of object being validated (Audit, UploadPrecheck, etc.)",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "data_file_type",
                    models.ForeignKey(
                        help_text="Type of data file being validated",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="depot.datafiletype",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_validation_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Validation Run",
                "verbose_name_plural": "Validation Runs",
                "db_table": "depot_validation_run",
                "ordering": ["-created_at"],
            },
            bases=(
                models.Model,
                depot.models.revisionmixin.RevisionMixin,
                depot.mixins.timestamp.TimestampMixin,
            ),
        ),
        migrations.CreateModel(
            name="ValidationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "validation_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of validation (key from VALIDATION_REGISTRY)",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0, help_text="Percentage complete (0-100)"
                    ),
                ),
                (
                    "result_summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Summary statistics (counts, percentages, metadata)",
                    ),
                ),
                (
                    "result_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed results (configuration, thresholds, etc.)",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if job failed", null=True
                    ),
                ),
                (
                    "error_traceback",
                    models.TextField(
                        blank=True, help_text="Full traceback if job failed", null=True
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Celery task ID for this job",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this job started processing",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When this job completed", null=True
                    ),
                ),
                (
                    "validation_run",
                    models.ForeignKey(
                        help_text="Parent validation run",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_jobs",
                        to="depot.validationrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Validation Job",
                "verbose_name_plural": "Validation Jobs",
                "db_table": "depot_validation_job",
                "ordering": ["created_at"],
            },
            bases=(
                models.Model,
                depot.models.revisionmixin.RevisionMixin,
                depot.mixins.timestamp.TimestampMixin,
            ),
        ),
        migrations.CreateModel(
            name="ValidationIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("error", "Error"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                        ],
                        db_index=True,
                        help_text="Severity level of this issue",
                        max_length=20,
                    ),
                ),
                (
                    "row_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Row number where issue was found (1-indexed)",
                        null=True,
                    ),
                ),
                (
                    "column_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Column name where issue was found",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "issue_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of validation failure (e.g., 'required_field_missing')",
                        max_length=100,
                    ),
                ),
                ("message", models.TextField(help_text="Human-readable error message")),
                (
                    "invalid_value",
                    models.TextField(
                        blank=True,
                        help_text="The invalid value that was found",
                        null=True,
                    ),
                ),
                (
                    "expected_value",
                    models.TextField(
                        blank=True,
                        help_text="What the value should be or look like",
                        null=True,
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context data (e.g., related values, constraints)",
                    ),
                ),
                (
                    "validation_job",
                    models.ForeignKey(
                        help_text="Parent validation job",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="depot.validationjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Validation Issue",
                "verbose_name_plural": "Validation Issues",
                "db_table": "depot_validation_issue",
                "ordering": ["severity", "row_number"],
                "indexes": [
                    models.Index(
                        fields=["validation_job", "severity"],
                        name="depot_valid_validat_4df2c0_idx",
                    ),
                    models.Index(
                        fields=["issue_type", "severity"],
                        name="depot_valid_issue_t_3bd6de_idx",
                    ),
                    models.Index(
                        fields=["column_name", "severity"],
                        name="depot_valid_column__537819_idx",
                    ),
                ],
            },
            bases=(
                models.Model,
                depot.models.revisionmixin.RevisionMixin,
                depot.mixins.timestamp.TimestampMixin,
            ),
        ),
        migrations.AddIndex(
            model_name="validationrun",
            index=models.Index(
                fields=["status", "created_at"], name="depot_valid_status_8edd5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="validationrun",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="depot_valid_content_470769_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="validationrun",
            index=models.Index(
                fields=["data_file_type", "status"],
                name="depot_valid_data_fi_fecad0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="validationjob",
            index=models.Index(
                fields=["validation_run", "status"],
                name="depot_valid_validat_d4397b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="validationjob",
            index=models.Index(
                fields=["validation_type", "status"],
                name="depot_valid_validat_1a2712_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="validationjob",
            index=models.Index(
                fields=["celery_task_id"], name="depot_valid_celery__40154e_idx"
            ),
        ),
    ]
