# Generated by Django 5.0.9 on 2025-10-23 18:15

import depot.mixins.timestamp
import depot.models.revisionmixin
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("depot", "0010_add_validation_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataProcessingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mapping_key",
                    models.CharField(
                        default="passthrough",
                        help_text="Mapping identifier (e.g., 'cnics', 'standard', 'passthrough')",
                        max_length=100,
                    ),
                ),
                (
                    "mapping_version",
                    models.CharField(
                        default="1.0",
                        help_text="Mapping version (e.g., '1.0', '1.1')",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "raw_file_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "processed_file_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "changes_summary",
                    models.JSONField(
                        default=dict,
                        help_text="Summary of transformations: renamed columns, value remaps, defaults, warnings, errors",
                    ),
                ),
                ("row_count_in", models.IntegerField(default=0)),
                ("row_count_out", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "data_processing_logs",
                "ordering": ["-created_at"],
            },
            bases=(
                models.Model,
                depot.models.revisionmixin.RevisionMixin,
                depot.mixins.timestamp.TimestampMixin,
            ),
        ),
        migrations.CreateModel(
            name="ValidationCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rule_key",
                    models.CharField(
                        help_text="Validator identifier (e.g., 'type_is_boolean', 'range', 'no_duplicates')",
                        max_length=100,
                    ),
                ),
                (
                    "rule_params",
                    models.JSONField(
                        default=dict,
                        help_text="Rule parameters (e.g., {'min': 1900, 'max': 2025})",
                    ),
                ),
                (
                    "passed",
                    models.BooleanField(
                        default=False, help_text="Whether validation passed"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("warning", "Warning"), ("error", "Error")],
                        default="warning",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(help_text="Human-readable validation message"),
                ),
                (
                    "affected_row_count",
                    models.IntegerField(
                        default=0, help_text="Number of rows affected by this issue"
                    ),
                ),
                (
                    "row_numbers",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated row numbers (never with patient IDs)",
                        null=True,
                    ),
                ),
                (
                    "invalid_value",
                    models.CharField(
                        blank=True,
                        help_text="Example invalid value (only if not PHI-sensitive)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        default=dict, help_text="Additional rule-specific information"
                    ),
                ),
            ],
            options={
                "db_table": "validation_checks",
                "ordering": ["validation_variable", "rule_key"],
            },
            bases=(
                models.Model,
                depot.models.revisionmixin.RevisionMixin,
                depot.mixins.timestamp.TimestampMixin,
            ),
        ),
        migrations.CreateModel(
            name="ValidationVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "column_name",
                    models.CharField(
                        help_text="Column name from definition", max_length=100
                    ),
                ),
                (
                    "column_type",
                    models.CharField(
                        help_text="Data type from definition", max_length=50
                    ),
                ),
                (
                    "display_name",
                    models.CharField(help_text="Human-readable name", max_length=200),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("total_rows", models.IntegerField(default=0)),
                ("null_count", models.IntegerField(default=0)),
                ("empty_count", models.IntegerField(default=0)),
                ("valid_count", models.IntegerField(default=0)),
                ("invalid_count", models.IntegerField(default=0)),
                ("warning_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                (
                    "summary",
                    models.JSONField(
                        default=dict,
                        help_text="Variable-specific statistics (e.g., duplicate_count, out_of_range_count)",
                    ),
                ),
            ],
            options={
                "db_table": "validation_variables",
                "ordering": ["validation_run", "column_name"],
            },
            bases=(
                models.Model,
                depot.models.revisionmixin.RevisionMixin,
                depot.mixins.timestamp.TimestampMixin,
            ),
        ),
        migrations.RemoveField(
            model_name="validationissue",
            name="validation_job",
        ),
        migrations.RemoveField(
            model_name="validationjob",
            name="validation_run",
        ),
        migrations.AlterModelOptions(
            name="validationrun",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="validationrun",
            name="depot_valid_status_8edd5e_idx",
        ),
        migrations.RemoveIndex(
            model_name="validationrun",
            name="depot_valid_data_fi_fecad0_idx",
        ),
        migrations.RenameIndex(
            model_name="validationrun",
            new_name="validation__content_944b9e_idx",
            old_name="depot_valid_content_470769_idx",
        ),
        migrations.RemoveField(
            model_name="validationrun",
            name="completed_jobs",
        ),
        migrations.RemoveField(
            model_name="validationrun",
            name="failed_jobs",
        ),
        migrations.RemoveField(
            model_name="validationrun",
            name="initiated_by",
        ),
        migrations.RemoveField(
            model_name="validationrun",
            name="total_jobs",
        ),
        migrations.AddField(
            model_name="validationrun",
            name="completed_variables",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="validationrun",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="validationrun",
            name="processed_file_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="validationrun",
            name="raw_file_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="validationrun",
            name="total_variables",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="validationrun",
            name="variables_with_errors",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="validationrun",
            name="variables_with_warnings",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="validationrun",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="validationrun",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="validationrun",
            name="data_file_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="depot.datafiletype"
            ),
        ),
        migrations.AlterField(
            model_name="validationrun",
            name="duckdb_path",
            field=models.CharField(
                blank=True,
                help_text="Temporary DuckDB file path",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="validationrun",
            name="object_id",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="validationrun",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="validationrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="validationrun",
            index=models.Index(fields=["status"], name="validation__status_e53aa1_idx"),
        ),
        migrations.AddIndex(
            model_name="validationrun",
            index=models.Index(
                fields=["data_file_type"], name="validation__data_fi_52c718_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="validationrun",
            table="validation_runs",
        ),
        migrations.AddField(
            model_name="dataprocessinglog",
            name="cohort",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="depot.cohort",
            ),
        ),
        migrations.AddField(
            model_name="dataprocessinglog",
            name="data_file_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="depot.datafiletype"
            ),
        ),
        migrations.AddField(
            model_name="dataprocessinglog",
            name="validation_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="processing_logs",
                to="depot.validationrun",
            ),
        ),
        migrations.AddField(
            model_name="validationvariable",
            name="validation_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variables",
                to="depot.validationrun",
            ),
        ),
        migrations.AddField(
            model_name="validationcheck",
            name="validation_variable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checks",
                to="depot.validationvariable",
            ),
        ),
        migrations.DeleteModel(
            name="ValidationIssue",
        ),
        migrations.DeleteModel(
            name="ValidationJob",
        ),
        migrations.AddIndex(
            model_name="dataprocessinglog",
            index=models.Index(
                fields=["validation_run"], name="data_proces_validat_617f2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataprocessinglog",
            index=models.Index(
                fields=["cohort", "data_file_type"],
                name="data_proces_cohort__7b5f36_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dataprocessinglog",
            index=models.Index(fields=["status"], name="data_proces_status_9ac4db_idx"),
        ),
        migrations.AddIndex(
            model_name="dataprocessinglog",
            index=models.Index(
                fields=["mapping_key"], name="data_proces_mapping_70effd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="validationvariable",
            index=models.Index(
                fields=["validation_run", "status"],
                name="validation__validat_a91a32_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="validationvariable",
            index=models.Index(fields=["status"], name="validation__status_4208b5_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="validationvariable",
            unique_together={("validation_run", "column_name")},
        ),
        migrations.AddIndex(
            model_name="validationcheck",
            index=models.Index(
                fields=["validation_variable", "passed"],
                name="validation__validat_bd9c5d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="validationcheck",
            index=models.Index(
                fields=["severity"], name="validation__severit_1f0fae_idx"
            ),
        ),
    ]
