# Generated by Django 5.0.9 on 2025-10-29 00:30

import depot.mixins.timestamp
import depot.models.revisionmixin
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depot", "0013_datatablefile_latest_validation_run"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionValidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("total_runs", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("last_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_files", models.IntegerField(default=0)),
                ("files_with_errors", models.IntegerField(default=0)),
                ("files_with_warnings", models.IntegerField(default=0)),
                (
                    "patient_validation_summary",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "latest_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submission_summaries",
                        to="depot.validationrun",
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_summary",
                        to="depot.cohortsubmission",
                    ),
                ),
            ],
            options={
                "db_table": "depot_submission_validations",
                "ordering": ["-created_at"],
            },
            bases=(
                models.Model,
                depot.models.revisionmixin.RevisionMixin,
                depot.mixins.timestamp.TimestampMixin,
            ),
        ),
        migrations.AlterModelTable(
            name="validationrun",
            table="depot_validation_runs",
        ),
        migrations.AlterModelTable(
            name="validationvariable",
            table="depot_validation_variables",
        ),
        migrations.AlterModelTable(
            name="validationcheck",
            table="depot_validation_checks",
        ),
        migrations.AlterModelTable(
            name="dataprocessinglog",
            table="depot_data_processing_logs",
        ),
    ]
