# Generated by Django 5.0.9 on 2025-10-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("depot", "0014_submission_validation_overview"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="dataprocessinglog",
            new_name="depot_data__validat_404ad7_idx",
            old_name="data_proces_validat_617f2f_idx",
        ),
        migrations.RenameIndex(
            model_name="dataprocessinglog",
            new_name="depot_data__cohort__23318e_idx",
            old_name="data_proces_cohort__7b5f36_idx",
        ),
        migrations.RenameIndex(
            model_name="dataprocessinglog",
            new_name="depot_data__status_1a5a2b_idx",
            old_name="data_proces_status_9ac4db_idx",
        ),
        migrations.RenameIndex(
            model_name="dataprocessinglog",
            new_name="depot_data__mapping_0647a8_idx",
            old_name="data_proces_mapping_70effd_idx",
        ),
        migrations.RenameIndex(
            model_name="validationcheck",
            new_name="depot_valid_validat_2c7c76_idx",
            old_name="validation__validat_bd9c5d_idx",
        ),
        migrations.RenameIndex(
            model_name="validationcheck",
            new_name="depot_valid_severit_8fcc9e_idx",
            old_name="validation__severit_1f0fae_idx",
        ),
        migrations.RenameIndex(
            model_name="validationrun",
            new_name="depot_valid_content_71b2fa_idx",
            old_name="validation__content_944b9e_idx",
        ),
        migrations.RenameIndex(
            model_name="validationrun",
            new_name="depot_valid_status_c88988_idx",
            old_name="validation__status_e53aa1_idx",
        ),
        migrations.RenameIndex(
            model_name="validationrun",
            new_name="depot_valid_data_fi_f4805a_idx",
            old_name="validation__data_fi_52c718_idx",
        ),
        migrations.RenameIndex(
            model_name="validationvariable",
            new_name="depot_valid_validat_93755a_idx",
            old_name="validation__validat_a91a32_idx",
        ),
        migrations.RenameIndex(
            model_name="validationvariable",
            new_name="depot_valid_status_3976b2_idx",
            old_name="validation__status_4208b5_idx",
        ),
    ]
