# Generated by Django 5.0.9 on 2025-10-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "depot",
            "0015_rename_data_proces_validat_617f2f_idx_depot_data__validat_404ad7_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="datatablefile",
            name="processed_file_path",
            field=models.CharField(
                blank=True,
                help_text="NAS path for processed CSV/TSV file (with mapping applied, for analyst use)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="datatablefile",
            name="duckdb_file_path",
            field=models.CharField(
                blank=True,
                help_text="NAS path for DuckDB file (derived from processed file)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="datatablefile",
            name="raw_file_path",
            field=models.CharField(
                blank=True,
                help_text="NAS path for raw CSV/TSV file (as submitted by cohort)",
                max_length=500,
            ),
        ),
    ]
