# Generated by Django 5.0.9 on 2025-10-31 15:35

import depot.mixins.timestamp
import depot.models.revisionmixin
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depot", "0017_create_summary_models"),
    ]

    operations = [
        # Remove old upload_precheck fields first
        migrations.RemoveField(
            model_name="cohortsubmissionfile",
            name="upload_precheck",
        ),
        migrations.RemoveField(
            model_name="datatablefile",
            name="upload_precheck",
        ),
        # Delete old UploadPrecheck model
        migrations.DeleteModel(
            name="UploadPrecheck",
        ),
        migrations.AlterField(
            model_name="phifiletracking",
            name="action",
            field=models.CharField(
                choices=[
                    ("nas_raw_created", "Raw file created on NAS"),
                    ("nas_raw_deleted", "Raw file deleted from NAS"),
                    ("nas_duckdb_created", "DuckDB file created on NAS"),
                    ("nas_duckdb_deleted", "DuckDB file deleted from NAS"),
                    ("nas_report_created", "Report created on NAS"),
                    ("nas_report_deleted", "Report deleted from NAS"),
                    ("work_copy_created", "File copied to workspace"),
                    ("work_copy_deleted", "File deleted from workspace"),
                    ("conversion_started", "File conversion started"),
                    ("conversion_completed", "File conversion completed"),
                    ("conversion_failed", "File conversion failed"),
                    ("patient_id_extraction_started", "Patient ID extraction started"),
                    (
                        "patient_id_extraction_completed",
                        "Patient ID extraction completed",
                    ),
                    ("patient_id_extraction_failed", "Patient ID extraction failed"),
                    ("file_uploaded_via_stream", "File uploaded via streaming"),
                    ("file_uploaded_chunked", "File uploaded in chunks"),
                    ("file_downloaded_via_stream", "File downloaded via streaming"),
                    ("file_deleted_via_api", "File deleted via internal API"),
                    ("prefix_deleted_via_api", "Prefix deleted via internal API"),
                    ("scratch_cleanup", "Scratch directory cleanup"),
                    ("stream_started", "Streaming operation started"),
                    ("stream_completed", "Streaming operation completed"),
                    ("stream_failed", "Streaming operation failed"),
                    ("precheck_upload_staged", "Precheck validation upload staged"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="PrecheckRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing_duckdb", "Processing DuckDB"),
                            ("processing_notebook", "Processing Notebook"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                (
                    "file_path",
                    models.CharField(
                        blank=True, help_text="NAS storage path", max_length=500
                    ),
                ),
                ("result", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                (
                    "celery_task_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="depot.cohort",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Deprecated - use uploaded_by instead",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_precheck_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "data_file_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="depot.datafiletype",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_precheck_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_file",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to the uploaded file in storage",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="depot.uploadedfile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(
                models.Model,
                depot.models.revisionmixin.RevisionMixin,
                depot.mixins.timestamp.TimestampMixin,
            ),
        ),
    ]
