# Generated by Django 5.0.9 on 2025-11-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depot", "0018_rename_uploadprecheck"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="detected_encoding",
            field=models.CharField(
                blank=True,
                help_text="Detected file encoding (e.g., utf-8, latin-1)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="has_bom",
            field=models.BooleanField(
                default=False, help_text="Whether file has UTF-8 BOM marker"
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="has_crlf",
            field=models.BooleanField(
                default=False, help_text="Whether file has Windows line endings"
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="header_column_count",
            field=models.IntegerField(
                blank=True, help_text="Number of columns in header row", null=True
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="line_count",
            field=models.IntegerField(
                blank=True, help_text="Number of lines in file", null=True
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="validation_errors",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of validation errors found during pre-upload check",
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="validation_performed_at",
            field=models.DateTimeField(
                blank=True, help_text="When validation was performed", null=True
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("passed", "Passed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Pre-upload validation status",
                max_length=20,
            ),
        ),
    ]
