# Generated by Django 5.0.9 on 2025-11-14 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depot", "0021_fix_risk_factor_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validationrun",
            name="object_id",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="PrecheckValidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_filename", models.CharField(max_length=500)),
                (
                    "file_path",
                    models.CharField(
                        help_text="Path in scratch storage", max_length=1000
                    ),
                ),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                (
                    "file_hash",
                    models.CharField(
                        blank=True, help_text="SHA256 hash", max_length=64, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("analyzing_metadata", "Analyzing Metadata"),
                            ("checking_integrity", "Checking CSV Integrity"),
                            ("validating", "Running Validation"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("progress_percent", models.IntegerField(default=0)),
                ("encoding", models.CharField(blank=True, max_length=50, null=True)),
                ("has_bom", models.BooleanField(blank=True, null=True)),
                ("delimiter", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "has_crlf",
                    models.BooleanField(
                        blank=True,
                        help_text="Windows (CRLF) vs Unix (LF) line endings",
                        null=True,
                    ),
                ),
                (
                    "line_count",
                    models.IntegerField(
                        blank=True, help_text="Total number of lines in file", null=True
                    ),
                ),
                (
                    "header_column_count",
                    models.IntegerField(
                        blank=True, help_text="Number of columns in header", null=True
                    ),
                ),
                (
                    "columns",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of column names from header row",
                    ),
                ),
                ("total_rows", models.IntegerField(blank=True, null=True)),
                (
                    "malformed_rows",
                    models.JSONField(
                        default=list,
                        help_text="List of dicts with row number and column count info",
                    ),
                ),
                (
                    "patient_id_results",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Patient ID validation results: {total, valid, invalid, invalid_ids: []}",
                    ),
                ),
                (
                    "validation_errors",
                    models.JSONField(default=list, help_text="List of error messages"),
                ),
                (
                    "validation_warnings",
                    models.JSONField(
                        default=list, help_text="List of warning messages"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("error_traceback", models.TextField(blank=True, null=True)),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precheck_validations",
                        to="depot.cohort",
                    ),
                ),
                (
                    "cohort_submission",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional submission to validate patient IDs against",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="precheck_validations",
                        to="depot.cohortsubmission",
                    ),
                ),
                (
                    "data_file_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precheck_validations",
                        to="depot.datafiletype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precheck_validations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validation_run",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to ValidationRun for detailed per-variable validation results",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="precheck_validations",
                        to="depot.validationrun",
                    ),
                ),
            ],
            options={
                "db_table": "depot_precheck_validation",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="depot_prech_user_id_4397a5_idx",
                    ),
                    models.Index(
                        fields=["cohort", "created_at"],
                        name="depot_prech_cohort__18ba6e_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="depot_prech_status_23ab92_idx",
                    ),
                ],
            },
        ),
    ]
