# Generated by Django 5.0.9 on 2025-11-17 15:35

from django.db import migrations


def add_data_table_permissions(apps, schema_editor):
    """Add permissions for CohortSubmissionDataTable and DataTableFile to all groups."""
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Get content types for the new models
    try:
        data_table_ct = ContentType.objects.get(app_label='depot', model='cohortsubmissiondatatable')
        data_table_file_ct = ContentType.objects.get(app_label='depot', model='datatablefile')
    except ContentType.DoesNotExist:
        # If content types don't exist yet, skip (they'll be added when models are created)
        return

    # Get all permissions for these models
    data_table_perms = Permission.objects.filter(content_type=data_table_ct)
    data_table_file_perms = Permission.objects.filter(content_type=data_table_file_ct)

    # NA Accord Administrators - full access
    try:
        na_admin_group = Group.objects.get(name='NA Accord Administrators')
        na_admin_group.permissions.add(*data_table_perms)
        na_admin_group.permissions.add(*data_table_file_perms)
    except Group.DoesNotExist:
        pass

    # Cohort Managers - view, add, change
    try:
        cohort_manager_group = Group.objects.get(name='Cohort Managers')
        manager_perms = Permission.objects.filter(
            content_type__in=[data_table_ct, data_table_file_ct],
            codename__in=[
                'view_cohortsubmissiondatatable',
                'add_cohortsubmissiondatatable',
                'change_cohortsubmissiondatatable',
                'view_datatablefile',
                'add_datatablefile',
                'change_datatablefile',
            ]
        )
        cohort_manager_group.permissions.add(*manager_perms)
    except Group.DoesNotExist:
        pass

    # Cohort Viewers - view only
    try:
        cohort_viewer_group = Group.objects.get(name='Cohort Viewers')
        viewer_perms = Permission.objects.filter(
            content_type__in=[data_table_ct, data_table_file_ct],
            codename__in=[
                'view_cohortsubmissiondatatable',
                'view_datatablefile',
            ]
        )
        cohort_viewer_group.permissions.add(*viewer_perms)
    except Group.DoesNotExist:
        pass


def remove_data_table_permissions(apps, schema_editor):
    """Remove permissions (for rollback)."""
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    try:
        data_table_ct = ContentType.objects.get(app_label='depot', model='cohortsubmissiondatatable')
        data_table_file_ct = ContentType.objects.get(app_label='depot', model='datatablefile')

        # Remove from all groups
        for group in Group.objects.all():
            group.permissions.remove(
                *Permission.objects.filter(content_type__in=[data_table_ct, data_table_file_ct])
            )
    except ContentType.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("depot", "0022_add_precheck_validation"),
    ]

    operations = [
        migrations.RunPython(add_data_table_permissions, remove_data_table_permissions),
    ]
