# Generated by Django 5.0.9 on 2025-11-17 15:51

import django.db.models.deletion
from django.db import migrations, models


def clear_old_file_references(apps, schema_editor):
    """
    Clear any existing file references from SubmissionActivity before changing the model.
    This is safe because the file field is nullable.
    """
    SubmissionActivity = apps.get_model('depot', 'SubmissionActivity')
    
    # Count and clear any existing file references
    count = SubmissionActivity.objects.filter(file__isnull=False).count()
    if count > 0:
        print(f"Clearing {count} existing file references from SubmissionActivity before model change")
        SubmissionActivity.objects.filter(file__isnull=False).update(file=None)


def restore_file_references(apps, schema_editor):
    """Reverse migration - nothing to restore since we can't recover the old references"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("depot", "0023_add_data_table_permissions"),
    ]

    operations = [
        # Step 1: Clear existing file references before changing the model
        migrations.RunPython(clear_old_file_references, restore_file_references),
        
        # Step 2: Change the ForeignKey to point to DataTableFile
        migrations.AlterField(
            model_name="submissionactivity",
            name="file",
            field=models.ForeignKey(
                blank=True,
                help_text="Related file if activity is file-specific",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="depot.datatablefile",
            ),
        ),
        
        # Step 3: Remove foreign key relationships from deprecated models
        migrations.RemoveField(
            model_name="patientidvalidation",
            name="file",
        ),
        migrations.RemoveField(
            model_name="datafile",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="datafile",
            name="type",
        ),
        migrations.RemoveField(
            model_name="datafilesubmission",
            name="data_file",
        ),
        migrations.RemoveField(
            model_name="datafilesubmission",
            name="cohort",
        ),
        migrations.RemoveField(
            model_name="datafilesubmission",
            name="protocol_year",
        ),
        migrations.RemoveField(
            model_name="datafilesubmission",
            name="type",
        ),
        migrations.RemoveField(
            model_name="patientidvalidation",
            name="cohort_submission",
        ),
        
        # Step 4: Delete the deprecated models
        migrations.DeleteModel(
            name="CohortSubmissionFile",
        ),
        migrations.DeleteModel(
            name="DataFile",
        ),
        migrations.DeleteModel(
            name="DataFileSubmission",
        ),
        migrations.DeleteModel(
            name="PatientIDValidation",
        ),
    ]
