# Generated by Django 5.0.9 on 2025-12-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depot", "0024_update_submissionactivity_file_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Allows this user to log in. Uncheck instead of deleting accounts.",
                verbose_name="Active account",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Grants access to this admin site and allows managing all cohorts and submissions.",
                verbose_name="NA-ACCORD staff",
            ),
        ),
    ]
