# Generated by Django 5.0.9 on 2025-12-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depot", "0025_alter_user_is_active_alter_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="datatablefile",
            name="debug_submission",
            field=models.BooleanField(
                default=False,
                help_text="If true, file is stored for debugging/chain of custody only - no processing or validation",
            ),
        ),
    ]
